# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3329471a203b8a8d2c9dbba0796e1d306ff5a86e94a36ba66fa03a00181c7f9dc7e5e08da8fc403d41860572ee543793a42102651698d46ca6af852356def5b7

test:
  secret_key_base: 0e86d5253986c0ba354dd8e619524015b35f15d51f4d4664086bb68ad387699e9c0cedfa4ee954e53f8484449fd427fb71d72a5608111d9be3c5f420beae3935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
